### ISSUE TITLE
Stability Constant calculation problem in thermal_block

### ISSUE THREAD

**Issue by RokyC** [RBniCS/RBniCSx#2]
![image](https://user-images.githubusercontent.com/59686187/171543282-378d83d7-affa-4afe-a9c7-2478b3f3b877.png)
Here I'd like to ask you a question. In the tutorial-thermal_blockm, is the bilinear term a (μ ') missing when calculating the Stability Constant in min-θ?

**Comment by francesco-ballarin** [comment]
Hi @RokyC ,
I understand this deserves some explanation ;)

In the code we choose $\mu' = (1, *)$, where star denotes a value which is inessential (as it only appears on the right-hand side). Furthemore, we choose the $H^1$ seminorm as inner product. Therefore, the coercivity constant at $\mu'$ is equal to 1, and thus you do not see it in the code.

**Comment by RokyC** [comment]
Thank you for your patient reply, which has helped me a lot!
