### ISSUE TITLE
Error importing rbnicsx.backend

### ISSUE THREAD

**Issue by nhornischer** [RBniCS/RBniCSx#8]
**Importing rbnicsx.backend the following error occurs:**

**Error Message**
INFO:root:running build_ext
INFO:root:building 'rbnicsx_a263da371c4cd6ae87f59eee82957eda' extension
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/.cache
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/.cache/fenics
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs/fenicsx-env
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs/fenicsx-env/lib
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/rbnicsx
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/rbnicsx/_cpp
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/rbnicsx/_cpp/rbnicsx
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/rbnicsx/_cpp/rbnicsx/_backends
INFO:root:creating /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/rbnicsx/_cpp/rbnicsx/wrappers
INFO:root:/Users/user/anaconda3/envs/fenicsx-env/bin/mpicc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/user/anaconda3/envs/fenicsx-env/include -arch arm64 -fPIC -O2 -isystem /Users/user/anaconda3/envs/fenicsx-env/include -arch arm64 -I/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/pybind11/include -I/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/pybind11/include -I/Users/user/anaconda3/envs/fenicsx-env/include -I/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/mpi4py/include -I/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/numpy/core/include -I/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/petsc4py/include -I/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/slepc4py/include -I/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/pybind11/include -I/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/rbnicsx/_cpp -I/Users/user/.cache/fenics -I/Users/user/anaconda3/envs/fenicsx-env/include/python3.10 -c /Users/user/.cache/fenics/.rendered.rbnicsx_a263da371c4cd6ae87f59eee82957eda.cpp -o /var/folders/88/mrjcwx711gz_493k3j8119yw0000gn/T/tmpr38y3iry/Users/user/.cache/fenics/.rendered.rbnicsx_a263da371c4cd6ae87f59eee82957eda.o -std=c++11 -fvisibility=hidden -std=c++20 -DDOLFINX_VERSION=0.6.0 -DDOLFINX_VERSION=0.6.0 -DHAS_ADIOS2 -DHAS_SLEPC -DHAS_PTSCOTCH -DHAS_PARMETIS
/Users/user/anaconda3/envs/fenicsx-env/bin/mpicc: line 330: arm64-apple-darwin20.0.0-clang: command not found
Traceback (most recent call last):
  File "/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
  File "/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/Users/user/anaconda3/envs/fenicsx-env/lib/python3.10/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/Users/user/anaconda3/envs/fenicsx-env/bin/mpicc' failed with exit code 127

**Here is the list of installed packages:**
aom                       3.5.0                h7ea286d_0    conda-forge
beartype                  0.14.0                   pypi_0    pypi
blosc                     1.21.4               hc338f07_0    conda-forge
boost-cpp                 1.78.0               h9ed8d21_3    conda-forge
brotli                    1.0.9                h1a8c8d9_8    conda-forge
brotli-bin                1.0.9                h1a8c8d9_8    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
ca-certificates           2023.5.7             hf0a4a13_0    conda-forge
cairo                     1.16.0            h1e71087_1016    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h2399d43_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7           py310h2887b22_0    conda-forge
cppimport                 22.8.2                   pypi_0    pypi
curl                      8.1.2                h912dcd9_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dlrbnicsx                 0.0.dev1                 pypi_0    pypi
double-conversion         3.2.0                hb7217d7_1    conda-forge
eigen                     3.4.0                hc021e02_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
fenics-basix              0.6.0           py310h2887b22_0    conda-forge
fenics-dolfinx            0.6.0           py310habe3afa_101    conda-forge
fenics-ffcx               0.6.0              pyh56297ac_0    conda-forge
fenics-libbasix           0.6.0                hf081368_0    conda-forge
fenics-libdolfinx         0.6.0              h9d5e15a_101    conda-forge
fenics-ufcx               0.6.0                h56297ac_0    conda-forge
fenics-ufl                2023.1.1           pyhd8ed1ab_1    conda-forge
ffmpeg                    4.4.2           gpl_hf318d42_112    conda-forge
fftw                      3.3.10          mpi_mpich_h0cb5807_7    conda-forge
filelock                  3.12.0                   pypi_0    pypi
fltk                      1.3.8                h38c865a_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.39.4          py310h2aa6e3c_0    conda-forge
freeimage                 3.18.0              hb513136_10    conda-forge
freetype                  2.12.1               hd633e50_1    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
gl2ps                     1.4.2                h17b34a0_0    conda-forge
glew                      2.1.0                h9f76cd9_2    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gmsh                      4.11.1               h6e0c8fd_2    conda-forge
gnutls                    3.7.8                h9f1a10d_0    conda-forge
hdf4                      4.2.15               h1a38d6a_5    conda-forge
hdf5                      1.12.2          mpi_mpich_h4e1c725_1    conda-forge
hypre                     2.25.0          mpi_mpich_h060cf3c_0    conda-forge
icu                       72.1                 he12128b_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imath                     3.1.6                hb5ab8b9_1    conda-forge
jpeg                      9e                   h1a8c8d9_3    conda-forge
jsoncpp                   1.9.5                hc021e02_1    conda-forge
jxrlib                    1.1                  h27ca646_2    conda-forge
kiwisolver                1.4.4           py310h2887b22_1    conda-forge
krb5                      1.20.1               h69eda48_0    conda-forge
lame                      3.100             h1a8c8d9_1003    conda-forge
lcms2                     2.14                 h8193b64_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libadios2                 2.8.3           mpi_mpich_h4f585cb_5    conda-forge
libaec                    1.0.6                hb7217d7_1    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_8    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_8    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_8    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcurl                   8.1.2                h912dcd9_0    conda-forge
libcxx                    16.0.4               h4653b0c_0    conda-forge
libdeflate                1.14                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libglib                   2.76.3               h24e9cb9_0    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libidn2                   2.3.4                h1a8c8d9_0    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libnetcdf                 4.8.1           mpi_mpich_h8e475c3_6    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libogg                    1.3.4                h27ca646_1    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libraw                    0.20.2               h1a38d6a_2    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.42.0               hb31c410_0    conda-forge
libssh2                   1.10.0               h7a5bd25_3    conda-forge
libtasn1                  4.19.0               h1a8c8d9_0    conda-forge
libtheora                 1.1.1             h3422bc3_1005    conda-forge
libtiff                   4.4.0                heb92581_5    conda-forge
libunistring              0.9.10               h3422bc3_0    conda-forge
libvorbis                 1.3.7                h9f76cd9_0    conda-forge
libvpx                    1.11.0               hc470f4d_3    conda-forge
libwebp-base              1.3.0                h1a8c8d9_0    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libxml2                   2.10.4               h2aff0a6_0    conda-forge
libzip                    1.9.2                h76ab92c_1    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
llvm-openmp               16.0.4               h1c12783_0    conda-forge
loguru                    0.7.0           py310hbe9552e_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
mako                      1.2.4                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1           py310hb6292c7_0    conda-forge
matplotlib-base           3.7.1           py310h78c5c2f_0    conda-forge
mdfenicsx                 0.1                      pypi_0    pypi
metis                     5.1.0             h9f76cd9_1006    conda-forge
mpfr                      4.2.0                he09a6ba_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.1.4           py310hb6d4c64_0    conda-forge
mpich                     4.0.3              hd4b5bf3_100    conda-forge
mumps-include             5.2.1               hce30654_11    conda-forge
mumps-mpi                 5.2.1               hfd295ca_11    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
nettle                    3.8.1                h63371fa_1    conda-forge
numpy                     1.24.3          py310haa1e00c_0    conda-forge
occt                      7.7.1           novtk_h5f4376a_101    conda-forge
openexr                   3.1.5                h25aad90_2    conda-forge
openh264                  2.3.1                hb7217d7_2    conda-forge
openjpeg                  2.5.0                h5d4e404_1    conda-forge
openssl                   3.1.1                h53f4e23_1    conda-forge
p11-kit                   0.24.1               h29577a5_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
parmetis                  4.0.3             hefa2a9d_1005    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
petsc                     3.17.4          real_hce0f69b_101    conda-forge
petsc4py                  3.17.4          real_hd154c65_101    conda-forge
pillow                    9.2.0           py310h9337a76_3    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
pkg-config                0.29.2            hab62308_1008    conda-forge
platformdirs              3.5.1              pyhd8ed1ab_0    conda-forge
plum-dispatch             2.1.0                    pypi_0    pypi
pooch                     1.7.0              pyha770c72_3    conda-forge
proj                      9.0.1                h4c79c2b_1    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptscotch                  6.0.9                hd02db47_2    conda-forge
pugixml                   1.11.4               hbdafb3b_0    conda-forge
pybind11                  2.10.4                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.11         h3ba56d0_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-gmsh               4.11.1               h57928b3_2    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pyvista                   0.39.1             pyhd8ed1ab_0    conda-forge
rapidjson                 1.1.0             hc88da5d_1002    conda-forge
rbnicsx                   0.0.dev1                 pypi_0    pypi
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
scalapack                 2.2.0                hb170938_1    conda-forge
scooby                    0.7.2              pyhd8ed1ab_0    conda-forge
scotch                    6.0.9                h7537618_2    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slepc                     3.17.2          real_h5400d42_100    conda-forge
slepc4py                  3.17.2          real_h01a885d_101    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
sqlite                    3.42.0               h203b68d_0    conda-forge
suitesparse               5.10.1               h7cd81ec_1    conda-forge
superlu                   5.2.2                hc615359_0    conda-forge
superlu_dist              7.2.0                h7df07b8_0    conda-forge
svt-av1                   1.4.1                h7ea286d_0    conda-forge
tbb                       2021.9.0             hffc8910_0    conda-forge
tbb-devel                 2021.9.0             h4f9cb39_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tornado                   6.3.2           py310h2aa6e3c_0    conda-forge
typing-extensions         4.6.3                hd8ed1ab_0    conda-forge
typing_extensions         4.6.3              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
unicodedata2              15.0.0          py310h8e9501a_0    conda-forge
urllib3                   2.0.2              pyhd8ed1ab_0    conda-forge
utfcpp                    3.2.3                hce30654_0    conda-forge
vtk                       9.1.0           qt_py310hafcb908_212    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h57fd34a_2    conda-forge
x265                      3.5                  hbc6ce65_3    conda-forge
xorg-fixesproto           5.0               h3422bc3_1002    conda-forge
xorg-kbproto              1.0.7             h27ca646_1002    conda-forge
xorg-libice               1.1.1                hb547adb_0    conda-forge
xorg-libsm                1.2.4                hb547adb_0    conda-forge
xorg-libx11               1.8.4                h1a8c8d9_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xorg-libxext              1.3.4                h1a8c8d9_2    conda-forge
xorg-libxfixes            5.0.3             h3422bc3_1004    conda-forge
xorg-libxrender           0.9.10            h27ca646_1003    conda-forge
xorg-renderproto          0.11.1            h27ca646_1002    conda-forge
xorg-xextproto            7.3.0             h1a8c8d9_1003    conda-forge
xorg-xproto               7.0.31            h27ca646_1007    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zfp                       0.5.5                hcfdfaf5_8    conda-forge
zlib                      1.2.13               h03a7124_4    conda-forge
zstd                      1.5.2                hf913c23_6    conda-forge

**I suppose the main error is "/Users/user/anaconda3/envs/fenicsx-env/bin/mpicc: line 330: arm64-apple-darwin20.0.0-clang: command not found", but I don't know how to fix it.**

**Comment by francesco-ballarin** [comment]
The relevant bit is
> /Users/user/anaconda3/envs/fenicsx-env/bin/mpicc: line 330: arm64-apple-darwin20.0.0-clang: command not found

Can you double check if that compiler is installed?

**Comment by nhornischer** [comment]
The clang compiler is installed but for a different target:

$ clang --version
  Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  Target: arm64-apple-darwin22.5.0
  Thread model: posix
  InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by francesco-ballarin** [comment]
Maybe install this https://anaconda.org/conda-forge/clang_osx-arm64 ?

**Comment by nhornischer** [comment]
Was already installed. Also reinstalling it did not solve the issue.

**Comment by francesco-ballarin** [comment]
Can you try running `export CC=clang CXX=clang` before running `python3 -c 'import rbnicsx.backends'`?

**Comment by nhornischer** [comment]
I fixed the issue by running the code in a docker container, now there are no problems with the compiler when installing rbnicsx.backend.
